config/routes.rb
CdnShop::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    get "/sale" => "home#sale"
    get "/find_order" => "track_order#find_order"
    get "/compare_product" => "home#compare_product"
    get "/find_matched" => "home#find_matched"
    get "/find_texons" => "home#find_texons"
    get "/find_products" => "home#find_products"
    get "/contact_us" => "home#contact_us"
    get "/about_us" => "home#about_us"
    post "/contact_info" => "home#contact_info"
    get "/listing_product" => "home#listing_product"
    get "/find_2_texons" => "home#find_2_texons"
    get "/find_2_products" => "home#find_2_products"
    get "/add_review" => "products#add_review"
    get "/check_avalability" => "products#check_avalability"
    resources :ratings, only: :update
  end

end

app/models/spree/base_decorator.rb
module Spree
	Spree::Core::Search::Base.class_eval do
    def get_base_scope
      base_scope = Spree::Product.active
      base_scope = base_scope.in_all_taxons(taxon) unless taxon.blank?
      base_scope = get_products_conditions_for(base_scope, keywords)
      base_scope = add_search_scopes(base_scope)
      base_scope
    end
	end
end

app/models/spree/product_decorator.rb
module Spree
	Spree::Product.class_eval do
	  has_many :ratings
    has_many :product_reviews
    belongs_to :user	
    add_search_scope :in_all_taxons do |*taxons|
        taxons = get_taxons(taxons)
        id = arel_table[:id]
        joins(:taxons).where(spree_taxons: { id: taxons }).group(id).having(id.count.eq(taxons.size))
    end


    def average_rating
	    ratings.sum(:score) / ratings.count
	  end

	end
end

app/models/spree/product_review.rb
module Spree
	class ProductReview < ActiveRecord::Base
		belongs_to :product
		belongs_to :user	
	end
end

app/models/spree/rating.rb
module Spree
	class Rating < ActiveRecord::Base
	  belongs_to :product
	  belongs_to :user
	end
end	

app/models/spree/user_decorator .rb
module Spree
	Spree::User.class_eval do
  	has_many :ratings
  	has_many :products
	end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    alias_method :orig_price_in, :price_in
    def price_in(currency)
      return orig_price_in(currency) unless sale_price.present?
      Spree::Price.new(:variant_id => self.id, :amount => self.sale_price, :currency => currency)
    end
  end
end

app/controllers/spree/home_controller_decorator.rb
module Spree
  HomeController.class_eval do

    def sale
      @products = Product.joins(:variants_including_master).where('spree_variants.sale_price is not null').uniq
    end

    def contact_us
    end

    def index
      slider = Spree::Taxon.where(:name => 'Slider').first
      @slider_products = slider.products.active if slider

      featured = Spree::Taxon.where(:name => 'Featured').first
      @featured_products = featured.products.active if featured

      latest = Spree::Taxon.where(:name => 'Latest').first
      @latest_products = latest.products.active if latest
    end
      
    def compare_product
      product_ids = []
       if !params[:product_ids].blank?
        params[:product_ids].each do |id|
          product_ids << id[:p_id]
        end
        @main_product = Spree::Product.where("id = ?", params[:main_product_id])
        product_ids= product_ids.reject(&:blank?)
        @products = Spree::Product.where("id IN(?)", product_ids)
        @product_properties = Spree::ProductProperty.where('product_id IN(?)', product_ids)

      else 
    	  @taxonomies = Spree::Taxonomy.all
      end
		end

    def find_matched
      @taxon = Spree::Taxon.where("id = ?", params[:taxon_id] )
      @taxon2 = Spree::Taxon.where("id = ?", params[:taxon_id2] )
    	@product = Spree::Product.where("id = ?", params[:product_id])
    	@product1 = Spree::Product.where("id = ?", params[:product_sec])
      @product_properties1 = Spree::ProductProperty.where('product_id = ?', params[:product_id])
      @product_properties2 = Spree::ProductProperty.where('product_id = ?', params[:product_sec])
      
      render :partial =>  'spree/home/matched_products'
    end

    def find_texons
      @texon = Spree::Taxon.where("taxonomy_id = ?", params[:texonomy_id] )
      render :partial =>  'spree/home/find_brand'
      #render :json => {:texon =>  @texon} 
    end

    def find_2_texons
      @texon = Spree::Taxon.where("taxonomy_id = ?", params[:texonomy_id1] )
      render :partial =>  'spree/home/find_2_brand'
      #render :json => {:texon =>  @texon} 
    end

    def find_2_products
      taxon = Spree::Taxon.find(params[:texon_id])
      @products = taxon.products.ransack(params[:q]).result
      @products = @products.page(params[:page]).per(500 || params[:per_page])
      render :partial =>  'spree/home/find_2_products'
      #render :json => {:products =>  @products} 
    end   

    def contact_info
    end

    def about_us
    end  

    def find_products
      taxon = Spree::Taxon.find(params[:texon_id])
      @products = taxon.products.ransack(params[:q]).result
      @products = @products.page(params[:page]).per(500 || params[:per_page])
      render :partial =>  'spree/home/find_products'
    end

    def listing_product 
      products = []
      @products = Spree::Product.joins("JOIN spree_products_taxons on spree_products_taxons.product_id = spree_products.id
                      JOIN spree_taxons on spree_products_taxons.taxon_id = spree_taxons.id")
              .where("spree_products_taxons.taxon_id IN(?)", params[:taxon_ids])

      products = @products.collect{|p|p.id}
     
      arr1 = params[:first]
      arr2 = params[:second]
      conditions = []
      unless arr1.blank?
        arr1.each_with_index do |price, index|
          if arr2[index].to_i != 0
            conditions << "(spree_prices.amount BETWEEN #{price.to_i} AND #{arr2[index].to_i} )"
          else
            conditions << "(spree_prices.amount > #{price.to_i} )"
          end
        end
      end
      if conditions.blank?
        if not products.blank?
          @filtered_products = Spree::Product.where("id IN(?)", products)
        else
          @filtered_products = Spree::Product.all
        end
      else
        if not products.blank?
          @filtered_products = Spree::Product.where("spree_products.id IN(?) AND (#{conditions.join(' OR ')}) AND spree_prices.currency = 'USD'", products)
          .joins("INNER JOIN spree_variants ON spree_variants.product_id = spree_products.id
                  INNER JOIN spree_prices ON spree_prices.variant_id = spree_variants.id").distinct
        else
          @filtered_products = Spree::Product.where("(#{conditions.join(' OR ')}) AND spree_prices.currency = 'USD'")
          .joins("INNER JOIN spree_variants ON spree_variants.product_id = spree_products.id
                  INNER JOIN spree_prices ON spree_prices.variant_id = spree_variants.id").distinct
        end
      end
      
    end
  end
end

app/controllers/spree/products_controller_decorator.rb
module Spree
  ProductsController.class_eval do


    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html


    def show
      return unless @product

      @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
      @product_properties = @product.product_properties.includes(:property)

      referer = request.env['HTTP_REFERER']
      if referer
        begin
          referer_path = URI.parse(request.env['HTTP_REFERER']).path
          # Fix for #2249
        rescue URI::InvalidURIError
          # Do nothing
        else
          if referer_path && referer_path.match(/\/t\/(.*)/)
            @taxon = Spree::Taxon.find_by_permalink($1)
          end
        end
      end
    end


    def check_avalability
      @stock_count = Spree::StockLocation.where('zipcode = ? ', params[:zipcode]).count 
    end
  end
end

app/controllers/spree/ratings_controller.rb
module Spree
  class RatingsController  < Spree::StoreController

    def update
      @rating = Spree::Rating.find(params[:id])
      @product = @rating.product
      if @rating.update_attributes(score: params[:score])
        respond_to do |format|
          format.js
        end
      end
    end
  end
end

app/controllers/spree/track_order_controller.rb
module Spree
  class TrackOrderController < Spree::StoreController
    def find_order
      order = params[:order_number].strip
      @order = Spree::Order.find_by_number(order)
      @ship_state = Spree::Shipment.find_by_order_id(@order.id)
      @payment = Spree::Payment.find_by_order_id(@order.id)
    end

  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelper
   def taxons_tree(root_taxon, current_taxon, max_level = 1)
      return '' if max_level < 1 || root_taxon.children.empty?
      content_tag :ul, class: 'taxons-list' do
        root_taxon.children.map do |taxon|
          css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
          
          content_tag :div, class: css_class do
              taxonomy = Spree::Taxonomy.find_by_id(taxon[:taxonomy_id])
              price = taxon.name.split("-")
            if taxonomy.name == "Price" 
              check_box_tag("taxon[]", taxon.id )  +
              label(:taxon, "    #{taxon.name}")  
                check_box_tag("taxon[#{taxonomy.name}][]", taxon.id, nil, :class => "price_sub", :range_first =>  price[0].to_f, :range_second =>  price[1].to_f  )  +
              label(:taxon, "    #{taxon.name}")
            else
              check_box_tag("taxon[]", taxon.id )  +
              label(:taxon, "    #{taxon.name}")  
                check_box_tag("taxon[#{taxonomy.name}][]", taxon.id, nil, :class => "submittable", :data => taxonomy.id, :range_first =>  price[0].to_f, :range_second =>  price[1].to_f  )  +
              label(:taxon, "    #{taxon.name}")
            end  
         end
        end.join("\n").html_safe
      end
    end
  end
end     

app/views/spree/shared/_check_avalability.html.erb
<% if !@product.relations.blank? %>
	<h6 class="product-section-title"><%= Spree.t(:look_for_similar_items) %></h6>
	
  <%= form_tag compare_product_path, :method => :get, :id => "link_to_compare" do %>
    <ul id="products" class="inline product-listing" data-hook="">
    	<% @product.relations.each_with_index do |relation, index| %>
    	   <% related_product = Spree::Product.find_by_id( relation.related_to_id ) %>
        <li class="product-row">
        	<ul>
        		<li style="margin: 0px 32px 0px 0px;">
        			<div id="product_<%= related_product.id%>" data="<%= related_product.id%>"class="box">
        				<%= small_image(related_product)%>
                <h6 class="product-section-head"><%= link_to truncate(related_product.name, :length => 50), related_product, :class => 'product-name', :title => related_product.name %></h6><br>
                <div style="margin-top: -21px;"class="price selling "><%= related_product.display_price %></div>
                <%= hidden_field_tag 'product_ids[][p_id]', nil , :id => "id_input_#{related_product.id}" %>
                <%= hidden_field_tag 'main_product_id', @product.id %>
        			</div>
        		</li>	
        	</ul>
        </li>
    	<% end %>
  	</ul>
    <%= submit_tag "Compare", :class => "large primary", :style=>"background-color: #4ab5e3 !important;" %>
  <% end %>	
<% end %>


<script>
  $(document).ready(function () {
    var ids = [];
  	$(".box").on("click",function() {
  		var product_id = $(this).attr('data');
  		if ($("#product_" + product_id).hasClass('picked')) {
        $("#product_" + product_id).removeClass('picked');
        $("#id_input_"+product_id).val('');
      } else {
        $("#product_" + product_id).addClass('picked');
        $("#id_input_"+ product_id).val(product_id);
      }
  	});

    $("#link_to_compare").submit(function() {
      var product_id = $(".box").attr('data');
      if ($("#product_" + product_id).hasClass('picked')) {
        return true
      } else {
        alert("Please select product for compare")
        return false
      }
    });

  });
</script>


<style type="text/css">
div.box {
  position: relative;
  /*border: groove;*/
  color: #000;
  padding: 20px;    
}
 
div.box:hover {
  cursor: hand;
  cursor: pointer;
  opacity: .9;
}
 
a.divLink {
  position: absolute;
  width: 100%;
  height: 50%;
  top: 0;
  left: 0;
  text-decoration: none;
  /* Makes sure the link doesn't get underlined */
  z-index: 10;
  /* raises anchor tag above everything else in div */
  /*background-color: white;*/
  /*workaround to make clickable in IE */
  opacity: 0;
  /*workaround to make clickable in IE */
  filter: alpha(opacity=0);
  /*workaround to make clickable in IE */
}




.select {
  position: absolute;
  top: 0;
  left: 0;
}

.deselect{
	position: absolute;
  top: 0;
  right: 0;
}

.picked{ background:rgb(202, 189, 189); }

</style>

app/views/spree/shared/_filters.html.erb
<% filters = @taxon ? @taxon.applicable_filters : [Spree::Core::ProductFilters.all_taxons] %>
<% unless filters.empty? %>
  <%= form_tag '', :method => :get, :id => 'sidebar_products_search' do %>
    <% params[:search] ||= {} %>
    <%= hidden_field_tag 'per_page', params[:per_page] %>
    <% filters.each do |filter| %>
      <% labels = filter[:labels] || filter[:conds].map {|m,c| [m,m]} %>
      <% next if labels.empty? %>
      <div class="navigation" data-hook="navigation">
        <h6 class="filter-title"> <%= filter[:name] %> </h6>
        <ul class="filter_choices">
          <% labels.each do |nm,val| %>
            <% label = "#{filter[:name]}_#{nm}".gsub(/\s+/,'_') %>
            <li class="nowrap">
              <input type="checkbox"
                     id="<%= label %>"
                     name="search[<%= filter[:scope].to_s %>][]"
                     value="<%= val %>"
                     <%= params[:search][filter[:scope]] && params[:search][filter[:scope]].include?(val.to_s) ? "checked" : "" %> />
              <label class="nowrap" for="<%= label %>"> <%= nm %> </label>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= submit_tag Spree.t(:search), :name => nil %>
  <% end %>
<% end %>

app/views/spree/shared/_footer.html.erb
<div id="" class="footer_dry">
	<div class="foot_wp">
		<div class="foot1">
  		<div class="foot_heading">
      	Our awards
      </div><!--foot_heading-->
      <span class="clear"></span>
      <p>Best British Brand 2011<br />CEW (UK) Beauty Awards</p>
      <p>Best Online Retailer 2014<br />Which? Awards</p>
  	</div><!--foot1-->
  	<div class="foot2">
  		<div class="foot_heading">
      	Can we help?
      </div><!--foot_heading-->
      <span class="clear"></span>
      <p>Call us: +91-731-403-5928  <br />Monday to Friday 9:30am – 10:00pm <br />Saturday 9:00am – 4:00pm</p>
      <p>Delivery information<br />Returns & refunds<br />Help online shopping</p>
  	</div><!--foot1-->
  	<div class="foot3">
   		<div class="foot_heading">
      	Be the first to know
      </div><!--foot_heading-->
      <span class="clear"></span>
      <div class="discover">Discover new products, offers and much more with our email updates
      </div>
      <div class="Social_media_wp">
      	<div class="Social_box">
          <span class="social_text">Join us on Facebook</span>
          <span class="social_icon"><a href="#"><img src="/assets/icon_facebook.jpg" /></a></span>
        </div><!--Social_box-->
        <span class="clear"></span>
        <div class="Social_box">
        	<span class="social_text">Follow us on Twitter</span>
          <span class="social_icon"><a href="#"><img src="/assets/icon_twitter.jpg" /></a></span>
        </div><!--Social_box-->
        <span class="clear"></span>
     	</div><!--Social_media_wp-->
    </div><!--foot1-->
</div>
  

app/views/spree/shared/_header.html.erb
<div class="wrap">
	<div class="header_Dry">
		<div class="logo_Dry"> <a href="/"><img src="/assets/cdn-logo.jpg" /></a>
    </div><!--logo_cdn-->

    <div class="right_links_wp">
  		<div class="top_nav_wp">
        
        
        <% if spree_user_signed_in? %>
        <a href="<%= account_path%>">My Account</a> | 
        <a href="<%= cart_path%>">My Cart</a> | 
        <a href="<%= destroy_spree_user_session_path %>" class="Left_padding_none">Logout</a> 
        <% else %>
          <a href="<%= create_new_session_path %>" class="Left_padding_none">Login</a> 
        <% end %> 
        <div class="Search_wp" style="position:absolute; margin-left: 16%;"> 
          <div class="Search_input_wp">
            <%= form_tag find_order_path, :method => :get, remote: true do %>
             <!-- <lable>Track your order </lable> -->
             <%= text_field_tag :order_number,nil, :class => 'title', :placeholder =>"Track Order", :style=>"background-color: #F2F2F2;" %>
              <%= submit_tag "Find", :class => "Search_btn order-btn"%>
            <% end %>
          </div><!--search_input_wp-->
        </div><!--Search_wp--> 
      </div><!--top_nav_wp-->
        <span class="clear"></span>
    </div><!--right_links_wp-->
      <span class="clear"></span>
  </div><!--header_Dry-->
                                          
	<div class="navigation_wp">
    <div class="nav_left_wp">
    	<%= render :partial => 'spree/shared/main_nav_bar' if store_menu? %>
    </div>
  </div>	
	</div>
</div>

app/views/spree/shared/_main_nav_bar.html.erb
<ul id="main-nav-bar" style="text-align:left;"class="inline" data-hook>
  <li><%= link_to Spree.t(:home), spree.root_path %></li>
  <li><%= link_to Spree.t(:shop), spree.products_path %></li>
  <li><%= link_to Spree.t(:compare), spree.compare_product_path %></li>
  <li><%= link_to Spree.t(:contact_us), spree.contact_us_path %></li>
  <li><%= link_to Spree.t(:about_us), spree.about_us_path %></li>
</ul>

app/views/spree/shared/_product_properties.html.erb
<% unless @product_properties.empty? %>  
  <h6 class="product-section-title"><%= Spree.t('properties')%></h6>
  <table id="product-properties" class="table-display" data-hook>
    <tbody>
      <% @product_properties.each do |product_property| %>
        <% css_class = cycle('even', 'odd', :name => "properties") %>
        <tr class="<%= css_class %>">
          <td><strong><%= product_property.property.presentation %></strong></td>
          <td><%= product_property.value %></td>
        </tr>
      <% end %>
      <% reset_cycle('properties') %>
    </tbody>
  </table>
<% end %>

app/views/spree/shared/_products.html.erb
<%
  paginated_products = @searcher.retrieve_products if params.key?(:keywords)
  paginated_products ||= products
%>

<% content_for :head do %>
  <% if paginated_products.respond_to?(:num_pages) %>
    <%= rel_next_prev_link_tags paginated_products %>
  <% end %>
<% end %>

<% if products.empty? %>
  <%= Spree.t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h6 class="search-results-title"><%= Spree.t(:search_results, :keywords => h(params[:keywords])) %></h6>
<% end %>
<div id="loader" class="block_left" style="">
  <img src="/assets/loading.gif" style="position:fixed; left:50%; top:50%;" >
</div>
<% if products.any? %>
<ul id="products" class="inline product-listing" data-hook>
  <% products.each do |product| %>
    <li id="product_<%= product.id %>" class="columns three <%= cycle("alpha", "secondary", "", "omega secondary", :name => "classes") %>" data-hook="products_list_item" itemscope itemtype="http://schema.org/Product">
      <div class="my-fluid-container">
        <%= link_to small_image(product, :itemprop => "image"), product, :itemprop => 'url' %>
      </div>
      <%= link_to truncate(product.name, :length => 50), product, :class => 'info', :itemprop => "name", :title => product.name %>
      <span class="price selling" itemprop="price"><%= display_price(product) %></span>
    </li>
  <% end %>
  <% reset_cycle("classes") %>
</ul>
<% end %>

<% if paginated_products.respond_to?(:num_pages) %>
  <%= paginate paginated_products %>
<% end %>

app/views/spree/shared/_properties_first.html.erb
<% unless @product_properties1.empty? %>  
  <h6 class="product-section-title"><%= Spree.t('properties')%></h6>
  <table id="product-properties" class="table-display" data-hook>
    <tbody>
      <% @product_properties1.each do |product_property| %>
        <% css_class = cycle('even', 'odd', :name => "properties") %>
        <tr class="<%= css_class %>">
          <td><strong><%= product_property.property.presentation %></strong></td>
          <td><%= product_property.value %></td>
        </tr>
      <% end %>
      <% reset_cycle('properties') %>
    </tbody>
  </table>
<% end %>

app/views/spree/shared/_properties_second.html.erb
<% unless @product_properties2.empty? %>  
  <h6 class="product-section-title"><%= Spree.t('properties')%></h6>
  <table id="product-properties" class="table-display" data-hook>
    <tbody>
      <% @product_properties2.each do |product_property| %>
        <% css_class = cycle('even', 'odd', :name => "properties") %>
        <tr class="<%= css_class %>">
          <td><strong><%= product_property.property.presentation %></strong></td>
          <td><%= product_property.value %></td>
        </tr>
      <% end %>
      <% reset_cycle('properties') %>
    </tbody>
  </table>
<% end %>

app/views/spree/shared/_slider.html.erb
<% if Spree::Slide.published.count > 0 %>
  <style type="text/css"> 
  .theme-default #slider {
      margin:0 auto 0 auto;
      width:618px; /* Make sure your images are the same size */
      height:246px; /* Make sure your images are the same size */
  }
  .slider-wrapper {
      margin:0 auto 50px auto;
  }
  </style>

  <div class="slider-wrapper theme-default">
    <div class="ribbon"></div>
    <div id="slider" class="nivoSlider">
      <% Spree::Slide.published.order('position ASC').each do |s| %>
        <% if s.body != "" %>
          <%= link_to image_tag(s.image.url, :title => '#' + s.name.to_url), s.link_url %>
        <% else %>
          <%= link_to image_tag(s.image.url), s.link_url %>
        <% end %>
      <% end %>
    </div>

    <% Spree::Slide.published.order('position ASC').each do |s| %>
      <div id='<%= s.name.to_url %>' class='nivo-html-caption'>
        <%= s.body.html_safe %>
      </div>
    <% end %>
  </div>

  <script type="text/javascript">
  $(window).load(function() {
      $('#slider').nivoSlider();
  });
  </script>
<% end %>

app/views/spree/shared/_taxonomies.html.erb
<nav id="" class="sidebar-item" data-hook>
  <% get_taxonomies.each do |taxonomy| %>
    <h6 class='taxonomy-root'><%= Spree.t(:shop_by_taxonomy, :taxonomy => taxonomy.name) %></h6>
    <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
  <% end %>
</nav>