config/routes.rb
CdnShop::Application.routes.draw do

  mount Spree::Core::Engine, :at => '/'

  Spree::Core::Engine.routes.draw do
    get "/sale" => "home#sale"
    get "/find_order" => "track_order#find_order"
    get "/compare_product" => "home#compare_product"
    get "/find_matched" => "home#find_matched"
    get "/find_texons" => "home#find_texons"
    get "/find_products" => "home#find_products"
    get "/contact_us" => "home#contact_us"
    get "/about_us" => "home#about_us"
    post "/contact_info" => "home#contact_info"
    get "/listing_product" => "home#listing_product"
    get "/find_2_texons" => "home#find_2_texons"
    get "/find_2_products" => "home#find_2_products"
    get "/add_review" => "products#add_review"
    get "/check_avalability" => "products#check_avalability"
    resources :ratings, only: :update
  end

end

app/models/spree/base_decorator.rb
module Spree
	Spree::Core::Search::Base.class_eval do
    def get_base_scope
      base_scope = Spree::Product.active
      base_scope = base_scope.in_all_taxons(taxon) unless taxon.blank?
      base_scope = get_products_conditions_for(base_scope, keywords)
      base_scope = add_search_scopes(base_scope)
      base_scope
    end
	end
end

app/models/spree/product_decorator.rb
module Spree
	Spree::Product.class_eval do
	  has_many :ratings
    has_many :product_reviews
    belongs_to :user	
    add_search_scope :in_all_taxons do |*taxons|
        taxons = get_taxons(taxons)
        id = arel_table[:id]
        joins(:taxons).where(spree_taxons: { id: taxons }).group(id).having(id.count.eq(taxons.size))
    end


    def average_rating
	    ratings.sum(:score) / ratings.count
	  end

	end
end

app/models/spree/product_review.rb
module Spree
	class ProductReview < ActiveRecord::Base
		belongs_to :product
		belongs_to :user	
	end
end

app/models/spree/rating.rb
module Spree
	class Rating < ActiveRecord::Base
	  belongs_to :product
	  belongs_to :user
	end
end	

app/models/spree/user_decorator .rb
module Spree
	Spree::User.class_eval do
  	has_many :ratings
  	has_many :products
	end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    alias_method :orig_price_in, :price_in
    def price_in(currency)
      return orig_price_in(currency) unless sale_price.present?
      Spree::Price.new(:variant_id => self.id, :amount => self.sale_price, :currency => currency)
    end
  end
end

app/controllers/spree/home_controller_decorator.rb
module Spree
  HomeController.class_eval do

    def sale
      @products = Product.joins(:variants_including_master).where('spree_variants.sale_price is not null').uniq
    end

    def contact_us
    end

    def index
      slider = Spree::Taxon.where(:name => 'Slider').first
      @slider_products = slider.products.active if slider

      featured = Spree::Taxon.where(:name => 'Featured').first
      @featured_products = featured.products.active if featured

      latest = Spree::Taxon.where(:name => 'Latest').first
      @latest_products = latest.products.active if latest
    end
      
    def compare_product
      product_ids = []
       if !params[:product_ids].blank?
        params[:product_ids].each do |id|
          product_ids << id[:p_id]
        end
        @main_product = Spree::Product.where("id = ?", params[:main_product_id])
        product_ids= product_ids.reject(&:blank?)
        @products = Spree::Product.where("id IN(?)", product_ids)
        @product_properties = Spree::ProductProperty.where('product_id IN(?)', product_ids)

      else 
    	  @taxonomies = Spree::Taxonomy.all
      end
		end

    def find_matched
      @taxon = Spree::Taxon.where("id = ?", params[:taxon_id] )
      @taxon2 = Spree::Taxon.where("id = ?", params[:taxon_id2] )
    	@product = Spree::Product.where("id = ?", params[:product_id])
    	@product1 = Spree::Product.where("id = ?", params[:product_sec])
      @product_properties1 = Spree::ProductProperty.where('product_id = ?', params[:product_id])
      @product_properties2 = Spree::ProductProperty.where('product_id = ?', params[:product_sec])
      
      render :partial =>  'spree/home/matched_products'
    end

    def find_texons
      @texon = Spree::Taxon.where("taxonomy_id = ?", params[:texonomy_id] )
      render :partial =>  'spree/home/find_brand'
      #render :json => {:texon =>  @texon} 
    end

    def find_2_texons
      @texon = Spree::Taxon.where("taxonomy_id = ?", params[:texonomy_id1] )
      render :partial =>  'spree/home/find_2_brand'
      #render :json => {:texon =>  @texon} 
    end

    def find_2_products
      taxon = Spree::Taxon.find(params[:texon_id])
      @products = taxon.products.ransack(params[:q]).result
      @products = @products.page(params[:page]).per(500 || params[:per_page])
      render :partial =>  'spree/home/find_2_products'
      #render :json => {:products =>  @products} 
    end   

    def contact_info
    end

    def about_us
    end  

    def find_products
      taxon = Spree::Taxon.find(params[:texon_id])
      @products = taxon.products.ransack(params[:q]).result
      @products = @products.page(params[:page]).per(500 || params[:per_page])
      render :partial =>  'spree/home/find_products'
    end

    def listing_product 
      products = []
      @products = Spree::Product.joins("JOIN spree_products_taxons on spree_products_taxons.product_id = spree_products.id
                      JOIN spree_taxons on spree_products_taxons.taxon_id = spree_taxons.id")
              .where("spree_products_taxons.taxon_id IN(?)", params[:taxon_ids])

      products = @products.collect{|p|p.id}
     
      arr1 = params[:first]
      arr2 = params[:second]
      conditions = []
      unless arr1.blank?
        arr1.each_with_index do |price, index|
          if arr2[index].to_i != 0
            conditions << "(spree_prices.amount BETWEEN #{price.to_i} AND #{arr2[index].to_i} )"
          else
            conditions << "(spree_prices.amount > #{price.to_i} )"
          end
        end
      end
      if conditions.blank?
        if not products.blank?
          @filtered_products = Spree::Product.where("id IN(?)", products)
        else
          @filtered_products = Spree::Product.all
        end
      else
        if not products.blank?
          @filtered_products = Spree::Product.where("spree_products.id IN(?) AND (#{conditions.join(' OR ')}) AND spree_prices.currency = 'USD'", products)
          .joins("INNER JOIN spree_variants ON spree_variants.product_id = spree_products.id
                  INNER JOIN spree_prices ON spree_prices.variant_id = spree_variants.id").distinct
        else
          @filtered_products = Spree::Product.where("(#{conditions.join(' OR ')}) AND spree_prices.currency = 'USD'")
          .joins("INNER JOIN spree_variants ON spree_variants.product_id = spree_products.id
                  INNER JOIN spree_prices ON spree_prices.variant_id = spree_variants.id").distinct
        end
      end
      
    end
  end
end

app/controllers/spree/products_controller_decorator.rb
module Spree
  ProductsController.class_eval do


    rescue_from ActiveRecord::RecordNotFound, :with => :render_404
    helper 'spree/taxons'

    respond_to :html


    def show
      return unless @product

      @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
      @product_properties = @product.product_properties.includes(:property)

      referer = request.env['HTTP_REFERER']
      if referer
        begin
          referer_path = URI.parse(request.env['HTTP_REFERER']).path
          # Fix for #2249
        rescue URI::InvalidURIError
          # Do nothing
        else
          if referer_path && referer_path.match(/\/t\/(.*)/)
            @taxon = Spree::Taxon.find_by_permalink($1)
          end
        end
      end
    end


    def check_avalability
      @stock_count = Spree::StockLocation.where('zipcode = ? ', params[:zipcode]).count 
    end
  end
end

app/controllers/spree/ratings_controller.rb
module Spree
  class RatingsController  < Spree::StoreController

    def update
      @rating = Spree::Rating.find(params[:id])
      @product = @rating.product
      if @rating.update_attributes(score: params[:score])
        respond_to do |format|
          format.js
        end
      end
    end
  end
end

app/controllers/spree/track_order_controller.rb
module Spree
  class TrackOrderController < Spree::StoreController
    def find_order
      order = params[:order_number].strip
      @order = Spree::Order.find_by_number(order)
      @ship_state = Spree::Shipment.find_by_order_id(@order.id)
      @payment = Spree::Payment.find_by_order_id(@order.id)
    end

  end
end

app/helpers/spree/base_helper_decorator.rb
module Spree
  module BaseHelper
   def taxons_tree(root_taxon, current_taxon, max_level = 1)
      return '' if max_level < 1 || root_taxon.children.empty?
      content_tag :ul, class: 'taxons-list' do
        root_taxon.children.map do |taxon|
          css_class = (current_taxon && current_taxon.self_and_ancestors.include?(taxon)) ? 'current' : nil
          
          content_tag :div, class: css_class do
              taxonomy = Spree::Taxonomy.find_by_id(taxon[:taxonomy_id])
              price = taxon.name.split("-")
            if taxonomy.name == "Price" 
              check_box_tag("taxon[]", taxon.id )  +
              label(:taxon, "    #{taxon.name}")  
                check_box_tag("taxon[#{taxonomy.name}][]", taxon.id, nil, :class => "price_sub", :range_first =>  price[0].to_f, :range_second =>  price[1].to_f  )  +
              label(:taxon, "    #{taxon.name}")
            else
              check_box_tag("taxon[]", taxon.id )  +
              label(:taxon, "    #{taxon.name}")  
                check_box_tag("taxon[#{taxonomy.name}][]", taxon.id, nil, :class => "submittable", :data => taxonomy.id, :range_first =>  price[0].to_f, :range_second =>  price[1].to_f  )  +
              label(:taxon, "    #{taxon.name}")
            end  
         end
        end.join("\n").html_safe
      end
    end
  end
end     

app/views/spree/home/_compare_products.html.erb
<div id="compare_container" data-hook="" class="container">
<% if !@products.blank? %>
  <% @products.each do |product| %>
     <div class=" col span_1_of_3"style="">
        <h6 class="product-section-head"><%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %></h6><br>
        <%= link_to product_image(product), product %>
        <div class="price selling "><%= product.display_price %></div>
        <%= render :partial => 'spree/shared/product_properties' %>
      </div> 
  <% end %>
<% end %>
</div>	
</div>

	

app/views/spree/home/_find_2_brand.html.erb
<% if !@texon.nil? %>
	<div class="field">
	  <%= select_tag 'taxon_id2', options_for_select(@texon.collect{ |c| [c.name, c.id] }),  :class => 'dropdown_menu',:prompt => "Select Brand" %>
	</div>
<% end %>	

app/views/spree/home/_find_2_products.html.erb
<% if !@products.nil? %>
	<div class="field">
	  <%= select_tag 'product_sec', options_for_select(@products.collect{ |c| [c.name, c.id] }),  :class => 'dropdown_menu',:prompt => "Select Product"  %>
	</div>
<% end %>	

app/views/spree/home/_find_products.html.erb
<% if !@products.nil? %>
	<div class="field">
	  <%= select_tag 'product_id', options_for_select(@products.collect{ |c| [c.name, c.id] }),  :class => 'dropdown_menu',:prompt => "Select Product" %>
	</div>
<% end %>	

app/views/spree/home/_product.html.erb
<li id="product_<%= product.id %>" class="columns four" data-hook="featured_products_list_item">
<div class="product-image">
  <%= link_to product_image(product), product %>
</div>
<%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %>
<div class="product-sku">
  <%= product.sku %>
</div>
<span class="price selling hidden"><%= product.display_price %></span>
</li>

app/views/spree/home/_slider.html.erb
<% if @slider_products %>
  <div id="home-slider">
    <ul>
      <% @slider_products.each do |product| %>
        <li>
          <div class="product-image">
            <%= link_to product_image(product), product %>
          </div>
          <div class="">
            <h1 class="product-title"><%= product.name %> - <%= product.sku %></h1>
            <div class="product-description">
              <%= product.description.to_s.html_safe %>
            </div>
            <div class="product-order-form">
              <%= form_for :order, :url => populate_orders_path do |f| %>
                <span class="product-price">
                  <%= product.display_price %>
                </span>
                <%= number_field_tag (product.has_variants? ? :quantity : "variants[#{product.master.id}]"),
                  1, :class => 'title', :in => 1..Spree::Stock::Quantifier.new(product.master).total_on_hand, :min => 1 %>
                <%= button_tag :id => 'add-to-cart-button', :type => :submit do %>
                  <%= content_tag(:i, '', :class => 'icon-plus') + " " + Spree.t(:add_to_cart) %>
                <% end %>
              <% end %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/spree/home/compare_product.html.erb
<div id="wrapper" data-hook="" class="container">
  <div class="bx-wrapper slider-pager"></div>
  <div id="content" class="columns sixteen" data-hook="">
    <div id="welcome-message">
      <div class="container">
        <% if @products.blank? %>
          <%= form_tag find_matched_path, :method => :get, remote: true, :id => "compare_product" do %>
            <h2 class="product-section-head"style="float: left; margin-top: -45px;"><%= Spree.t(:compare_product) %> </h2>
            <div class="alpha six columns">
              <h3 style="text-align: left;"><%= Spree.t(:first_product) %></h3>
              <div class="field hide_me" style="margin-top:-10px;  margin-left: -30px;">
                <%= select_tag 'taxonomy', options_for_select(@taxonomies.collect{ |c| [c.name, c.id] }),  :class => '',:prompt => "Select Category" %>
              </div>
              <div class="field hide_me" style="margin-top:-30px; float: left; margin-left: -55px;" id="texon_list">
                
              </div>
              <div class="field" style="margin-top: 10%; text-align: left; margin-left: -55px;" id="product_list">
               
              </div>
            </div>  
            <div class="omega six columns">
              <h3 style="text-align: left;"><%= Spree.t(:second_product) %></h3>
              <div class="field hide_me" style="margin-top:-10px; margin-left: -30px;">
                <%= select_tag 'taxonomy1', options_for_select(@taxonomies.collect{ |c| [c.name, c.id] }),  :class => '',:prompt => "Select Category" %>
              </div>
              <div class="field hide_me" style="margin-top:-30px; float: left; margin-left: -55px;" id="texon_list_sec">
              </div>
              <div class="field" style="margin-top: 10%; text-align: left; margin-left: -55px;" id="product_list1">
                
              </div>
            </div>  
            <%= submit_tag "Compare", :class => "large primary btn-compare", :style=>"background-color: #4ab5e3 !important;" %>
          <% end %>
          <% else %>
          <%= link_to_function "Back", "history.back()", :class => "back-url" %>
           <span style="float: left; margin-top: -5%;"><h6 class="product-section-head"><%= Spree.t(:compare_product) %></h6></span>
           <div id="compare_container" data-hook="" class="container"> 
            <% @main_product.each do |product| %>
              <div class="product_compare col span_1_of_3"style="">
                <h6 class="product-section-head"><%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %></h6><br>
                <%= link_to product_image(product), product %>
                <div class="price selling "><%= product.display_price %></div>
                <%= render :partial => 'spree/shared/product_properties' %>
              </div>
            <% end %>
            <% @products.each_with_index do |product, index| %>
              <div class="product_compare col span_1_of_3"style="">
                <h6 class="product-section-head"><%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %></h6><br>
                <%= link_to product_image(product), product %>
                <div class="price selling "><%= product.display_price %></div>
                <%= render :partial => 'spree/shared/product_properties' %>
              </div>
            <% end %>
          </div>
          <% end %>
      </div>
    </div>
  </div>  
</div>
<div id="compare_container" data-hook="" class="container">
  <% if not @product.blank? && @product1.blank? %>
    <h6 class="product-section-head">Compare
      <% @product.each do |product1| %>
        <%= product1.name %>
      <% end %> <%= Spree.t(:and) %>  
      
      <% @product1.each do |product1|%>
        <%= product1.name %>
      <% end %>
    </h6>
    <div class="section group" style="margin-top: 5%;">
      <% @product.each do |product| %>
        <div class=" col span_1_of_3"style="">
          <h6 class="product-section-head"><%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %></h6><br>
          <%= link_to product_image(product), product %>
          <div class="price selling "><%= product.display_price %></div>
          <%= render :partial => 'spree/shared/properties_first' %>
        </div>    
      <% end %>

      <% @product1.each do |product| %>
        <div class=" col span_3_of_3">
          <h6 class="product-section-head"><%= link_to truncate(product.name, :length => 50), product, :class => 'product-name', :title => product.name %></h6><br>
          <%= link_to product_image(product), product %>
          <div class="price selling "><%= product.display_price %></div>
            <%= render :partial => 'spree/shared/properties_second' %>
        </div>
      <% end %>
    </div>    
  <% end %> 
</div>
<script>
$( document ).ready(function() {
  $("#taxonomy").on("change", function(){
    var texonomy_id = $(this).val(),
      url = "/find_texons";
    $.ajax({
      type: "get",
      url: url,
      data: { texonomy_id: texonomy_id},
      success: function (data) {
        $("#texon_list").html(data)
      }
    })
  })

  $("#texon_list").on("change", "#taxon_id", function(){
    var texon_id = $(this).val(),
      url = "/find_products";
    $.ajax({
      type: "get",
      url: url,
      data: { texon_id: texon_id},
      success: function (data) {
        $('#product_list').html(data)
      }
    })
  })

  $("#taxonomy1").on("change", function(){
    var texonomy_id = $(this).val(),
      url = "/find_2_texons";
    $.ajax({
      type: "get",
      url: url,
      data: { texonomy_id1: texonomy_id},
      success: function (data) {
        $('#texon_list_sec').html(data)
      }
    })
  })

  $("#texon_list_sec").on("change", "#taxon_id2", function(){
    var texon_id = $(this).val(),
      url = "/find_2_products";
    $.ajax({
      type: "get",
      url: url,
      data: { texon_id: texon_id},
      success: function (data) {
        $('#product_list1').html(data)
      }
    })
  })

  $( "#compare_product" ).submit(function() {
    var taxon_id = $("#taxon_id").val(),
        taxon_id2 = $("#taxon_id2").val(),
        product_id = $("#product_id").val(),
        product_sec = $("#product_sec").val(),
        url = "/find_matched";
    if(product_id == "" || product_sec == ""){
      alert("Please Select Product")
      return false;
    }

    if(taxon_id =="" || taxon_id2 == ""){
      alert("Please Select Brand")
      return false;
    }    
    $.ajax({
      type: "get",
      url: url,
      data: {taxon_id: taxon_id, taxon_id2: taxon_id2, product_id: product_id, product_sec:product_sec},
      success: function (data) {
        $("#compare_container").html(data)
      }
    })
  })
});
</script>

app/views/spree/home/find_2_products.js.erb
$("#product_list1").html("<%= escape_javascript(render partial: 'spree/home/find_products') %>");

app/views/spree/home/find_2_texons.js.erb
$("#texon_list_sec").html("<%= escape_javascript(render partial: 'spree/home/find_2_brand') %>");

app/views/spree/home/find_matched.js.erb
$('#compare_container').html("<%= escape_javascript(render partial: 'spree/home/matched_products') %>");

app/views/spree/home/find_products.js.erb
$("#product_list").html("<%= escape_javascript(render partial: 'spree/home/find_2_products') %>");

app/views/spree/home/index.html.erb
<%= render 'slider' %>
<div class="container">
  <% if @featured_products %>
    <div id="featured-products" class="row">
      <h3>Featured Products</h3>
      <hr>
      <ul class="carousel">
        <% @featured_products.each do |product| %>
          <%= render 'product', :product => product %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if @latest_products %>
    <div id="latest-products" class="row">
      <h3>Latest Products</h3>
      <hr>
      <ul class="carousel">
        <% @latest_products.sort_by{ |product| product.created_at }.reverse.each do |product| %>
          <%= render 'product', :product => product %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/spree/home/listing_product.html.erb
<% content_for :sidebar do %>
  <div data-hook="homepage_sidebar_navigation">
    <%= form_tag listing_product_path, :method => :get, :id => 'sidebar_products_search' do %>
    
    <% if "spree/products" == params[:controller] && @taxon %>
      <%= render :partial => 'spree/shared/filters' %>
    <% else %>
      <%= render :partial => 'spree/shared/taxonomies' %>
    <% end %>
    <%= submit_tag Spree.t(:search), :name => nil %>
    <% end %>
  </div>
<% end %>


<div data-hook="search_results">
  <% if @filtered_products.blank? %>
    <h6 class="search-results-title"><%= Spree.t(:no_products_found) %></h6>
  <% else %>
    <%= render :partial => 'spree/shared/products', :locals => { :products => @filtered_products, :taxon => @taxon } %>
  <% end %>
</div>
  

app/views/spree/home/listing_product.js.erb
$('#content').html("<%= escape_javascript(render partial: 'spree/home/listing', locals: {products: @filtered_products}) %>");